augmentation:
  train: ~
  inference:
    - 
      name: resize
      size: 640
      interpolation: bilinear
      max_size: ~
      resize_criteria: long
    - 
      name: pad
      size: 640
      fill: 0
    -
      name: totensor
      pixel_range: 1.0
